version: '2'
services:

  squadminds_db:
    image: postgres
    volumes:
      - SquadMinds_DB:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'squadminds_user'
      POSTGRES_PASSWORD: 'squadminds_password'
      POSTGRES_DB: 'squadminds'
    ports:
      - "5432:5432"

  squadminds:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/squadminds
    ports:
      - "3000:3000"
    depends_on:
      - squadminds_db
    links:
      - squadminds_db
    environment:
      LAUNCHY_DRY_RUN: 'true'
      BROWSER: '/usr/bin/lynx'
      DATABASE_URL: postgresql://squadminds_user:squadminds_password@squadminds_db/squadminds
      RAILS_MAX_THREADS: 5

volumes:
  SquadMinds_DB:
    external: true
