default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: squadminds_dev

test:
  <<: *default
  database: squadminds_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
